packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@radix-ui/react-slot': ^1.2.2
  '@rsbuild/core': ^1.3.15
  '@rsbuild/plugin-react': ^1.3.0
  '@rsbuild/plugin-sass': ^1.3.1
  '@tailwindcss/postcss': ^4.1.6
  '@tanstack/eslint-config': ^0.3.0
  '@types/react': ^19.1.4
  '@types/react-dom': ^19.1.5
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.33.0
  lucide-react: ^0.511.0
  postcss: ^8.5.3
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwind-merge: ^3.3.0
  tailwindcss: ^4.1.6
  tw-animate-css: ^1.3.0
  typescript: ^5.8.3
