/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthTablesIndexRouteImport } from './routes/_auth/tables.index'
import { Route as AuthTablesTableIdRouteImport } from './routes/_auth/tables.$tableId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthTablesIndexRoute = AuthTablesIndexRouteImport.update({
  id: '/tables/',
  path: '/tables/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTablesTableIdRoute = AuthTablesTableIdRouteImport.update({
  id: '/tables/$tableId',
  path: '/tables/$tableId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/tables/$tableId': typeof AuthTablesTableIdRoute
  '/tables': typeof AuthTablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/tables/$tableId': typeof AuthTablesTableIdRoute
  '/tables': typeof AuthTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_auth/tables/$tableId': typeof AuthTablesTableIdRoute
  '/_auth/tables/': typeof AuthTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/tables/$tableId' | '/tables'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/tables/$tableId' | '/tables'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/_public/login'
    | '/_auth/tables/$tableId'
    | '/_auth/tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/tables/': {
      id: '/_auth/tables/'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AuthTablesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tables/$tableId': {
      id: '/_auth/tables/$tableId'
      path: '/tables/$tableId'
      fullPath: '/tables/$tableId'
      preLoaderRoute: typeof AuthTablesTableIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthTablesTableIdRoute: typeof AuthTablesTableIdRoute
  AuthTablesIndexRoute: typeof AuthTablesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthTablesTableIdRoute: AuthTablesTableIdRoute,
  AuthTablesIndexRoute: AuthTablesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
