/** @type {import('tailwindcss').Config} */
export default {
  content: [path.resolve(__dirname, "./src/**/*.{js,jsx,ts,tsx}")],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      primary: {
        50: "var(--color-primary-50)",
        100: "var(--color-primary-100)",
        200: "var(--color-primary-200)",
        300: "var(--color-primary-300)",
        400: "var(--color-primary-400)",
        500: "var(--color-primary-500)",
        600: "var(--color-primary-600)",
        700: "var(--color-primary-700)",
        800: "var(--color-primary-800)",
        900: "var(--color-primary-900)",
        950: "var(--color-primary-950)",
      },
      secondary: {
        50: "var(--color-secondary-50)",
        100: "var(--color-secondary-100)",
        200: "var(--color-secondary-200)",
        300: "var(--color-secondary-300)",
        400: "var(--color-secondary-400)",
        500: "var(--color-secondary-500)",
        600: "var(--color-secondary-600)",
        700: "var(--color-secondary-700)",
        800: "var(--color-secondary-800)",
        900: "var(--color-secondary-900)",
        950: "var(--color-secondary-950)",
      },
      neutral: {
        50: "var(--color-neutral-50)",
        100: "var(--color-neutral-100)",
        200: "var(--color-neutral-200)",
        300: "var(--color-neutral-300)",
        400: "var(--color-neutral-400)",
        500: "var(--color-neutral-500)",
        600: "var(--color-neutral-600)",
        700: "var(--color-neutral-700)",
        800: "var(--color-neutral-800)",
        900: "var(--color-neutral-900)",
        950: "var(--color-neutral-950)",
      },
      success: {
        50: "var(--color-success-50)",
        100: "var(--color-success-100)",
        500: "var(--color-success-500)",
        700: "var(--color-success-700)",
      },
      warning: {
        50: "var(--color-warning-50)",
        100: "var(--color-warning-100)",
        500: "var(--color-warning-500)",
        700: "var(--color-warning-700)",
      },
      error: {
        50: "var(--color-error-50)",
        100: "var(--color-error-100)",
        500: "var(--color-error-500)",
        700: "var(--color-error-700)",
      },
      info: {
        50: "var(--color-info-50)",
        100: "var(--color-info-100)",
        500: "var(--color-info-500)",
        700: "var(--color-info-700)",
      },
      white: "#FFFFFF",
      black: "#000000",
    },
    spacing: {
      px: "var(--spacing-px)",
      0: "var(--spacing-0)",
      0.5: "var(--spacing-0.5)",
      1: "var(--spacing-1)",
      1.5: "var(--spacing-1.5)",
      2: "var(--spacing-2)",
      2.5: "var(--spacing-2.5)",
      3: "var(--spacing-3)",
      3.5: "var(--spacing-3.5)",
      4: "var(--spacing-4)",
      5: "var(--spacing-5)",
      6: "var(--spacing-6)",
      7: "var(--spacing-7)",
      8: "var(--spacing-8)",
      9: "var(--spacing-9)",
      10: "var(--spacing-10)",
      11: "var(--spacing-11)",
      12: "var(--spacing-12)",
      14: "var(--spacing-14)",
      16: "var(--spacing-16)",
      20: "var(--spacing-20)",
      24: "var(--spacing-24)",
      28: "var(--spacing-28)",
      32: "var(--spacing-32)",
      36: "var(--spacing-36)",
      40: "var(--spacing-40)",
      44: "var(--spacing-44)",
      48: "var(--spacing-48)",
      52: "var(--spacing-52)",
      56: "var(--spacing-56)",
      60: "var(--spacing-60)",
      64: "var(--spacing-64)",
      72: "var(--spacing-72)",
      80: "var(--spacing-80)",
      96: "var(--spacing-96)",
    },
    fontFamily: {
      sans: "var(--font-family-sans)",
      serif: "var(--font-family-serif)",
      mono: "var(--font-family-mono)",
    },
    fontSize: {
      xs: "var(--font-size-xs)",
      sm: "var(--font-size-sm)",
      base: "var(--font-size-base)",
      lg: "var(--font-size-lg)",
      xl: "var(--font-size-xl)",
      "2xl": "var(--font-size-2xl)",
      "3xl": "var(--font-size-3xl)",
      "4xl": "var(--font-size-4xl)",
      "5xl": "var(--font-size-5xl)",
      "6xl": "var(--font-size-6xl)",
      "7xl": "var(--font-size-7xl)",
      "8xl": "var(--font-size-8xl)",
      "9xl": "var(--font-size-9xl)",
    },
    fontWeight: {
      thin: "var(--font-weight-thin)",
      extralight: "var(--font-weight-extralight)",
      light: "var(--font-weight-light)",
      normal: "var(--font-weight-normal)",
      medium: "var(--font-weight-medium)",
      semibold: "var(--font-weight-semibold)",
      bold: "var(--font-weight-bold)",
      extrabold: "var(--font-weight-extrabold)",
      black: "var(--font-weight-black)",
    },
    lineHeight: {
      none: "var(--line-height-none)",
      tight: "var(--line-height-tight)",
      snug: "var(--line-height-snug)",
      normal: "var(--line-height-normal)",
      relaxed: "var(--line-height-relaxed)",
      loose: "var(--line-height-loose)",
    },
    letterSpacing: {
      tighter: "var(--letter-spacing-tighter)",
      tight: "var(--letter-spacing-tight)",
      normal: "var(--letter-spacing-normal)",
      wide: "var(--letter-spacing-wide)",
      wider: "var(--letter-spacing-wider)",
      widest: "var(--letter-spacing-widest)",
    },
    borderRadius: {
      none: "var(--border-radius-none)",
      sm: "var(--border-radius-sm)",
      DEFAULT: "var(--border-radius-md)",
      md: "var(--border-radius-md)",
      lg: "var(--border-radius-lg)",
      xl: "var(--border-radius-xl)",
      "2xl": "var(--border-radius-2xl)",
      "3xl": "var(--border-radius-3xl)",
      full: "var(--border-radius-full)",
    },
    borderWidth: {
      0: "var(--border-width-0)",
      DEFAULT: "var(--border-width-1)",
      1: "var(--border-width-1)",
      2: "var(--border-width-2)",
      4: "var(--border-width-4)",
      8: "var(--border-width-8)",
    },
    boxShadow: {
      sm: "var(--shadow-sm)",
      DEFAULT: "var(--shadow-md)",
      md: "var(--shadow-md)",
      lg: "var(--shadow-lg)",
      xl: "var(--shadow-xl)",
      "2xl": "var(--shadow-2xl)",
      inner: "var(--shadow-inner)",
      none: "var(--shadow-none)",
    },
    extend: {
      transitionDuration: {
        75: "var(--animation-duration-75)",
        100: "var(--animation-duration-100)",
        150: "var(--animation-duration-150)",
        200: "var(--animation-duration-200)",
        300: "var(--animation-duration-300)",
        500: "var(--animation-duration-500)",
        700: "var(--animation-duration-700)",
        1000: "var(--animation-duration-1000)",
      },
      transitionTimingFunction: {
        in: "var(--animation-timing-in)",
        out: "var(--animation-timing-out)",
        "in-out": "var(--animation-timing-in-out)",
      },
    },
  },
  plugins: [],
};
