/**
 * Centralized error codes for the application.
 *
 * These codes are used in API error responses to provide consistent error identification.
 * Each code should be unique and descriptive of the error condition.
 *
 * This enum is shared between frontend and backend to ensure consistency.
 */

export enum EErrorCode {
  // Authentication & Authorization Errors (1000-1999)
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_INVALID = "TOKEN_INVALID",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",

  // Validation Errors (2000-2999)
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_INPUT = "INVALID_INPUT",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  INVALID_FORMAT = "INVALID_FORMAT",

  // Resource Errors (3000-3999)
  NOT_FOUND = "NOT_FOUND",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  CONFLICT = "CONFLICT",
  RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED",

  // Business Logic Errors (4000-4999)
  BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION",
  INVALID_STATE = "INVALID_STATE",
  OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED",

  // External Service Errors (5000-5999)
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  EXTERNAL_SERVICE_TIMEOUT = "EXTERNAL_SERVICE_TIMEOUT",
  EXTERNAL_SERVICE_UNAVAILABLE = "EXTERNAL_SERVICE_UNAVAILABLE",

  // Database Errors (6000-6999)
  DATABASE_ERROR = "DATABASE_ERROR",
  QUERY_FAILED = "QUERY_FAILED",
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
  UNIQUE_CONSTRAINT_VIOLATION = "UNIQUE_CONSTRAINT_VIOLATION",
  FOREIGN_KEY_CONSTRAINT_VIOLATION = "FOREIGN_KEY_CONSTRAINT_VIOLATION",

  // System Errors (7000-7999)
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  TIMEOUT = "TIMEOUT",
  BAD_REQUEST = "BAD_REQUEST",
  BAD_GATEWAY = "BAD_GATEWAY",
  GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT",
  SERVER_ERROR = "SERVER_ERROR",

  // Network & Connection Errors (7100-7199)
  NETWORK_ERROR = "NETWORK_ERROR",
  CONNECTION_ERROR = "CONNECTION_ERROR",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
  REQUEST_CANCELED = "REQUEST_CANCELED",
  REQUEST_CONFIG_ERROR = "REQUEST_CONFIG_ERROR",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",

  // File Errors (8000-8999)
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
  FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED",

  // Order-specific Errors (9000-9999)
  ORDER_ALREADY_PROCESSED = "ORDER_ALREADY_PROCESSED",
  ORDER_ITEM_NOT_AVAILABLE = "ORDER_ITEM_NOT_AVAILABLE",
  ORDER_CANNOT_BE_MODIFIED = "ORDER_CANNOT_BE_MODIFIED",

  // User-specific Errors (10000-10999)
  USER_NOT_ACTIVE = "USER_NOT_ACTIVE",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",

  // Payment Errors (11000-11999)
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_METHOD_INVALID = "PAYMENT_METHOD_INVALID",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",

  // Rate Limiting Errors (12000-12999)
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
}
